#!/bin/bash
echo 'Enter C file name (without the.c extension):'
read fname
echo -e "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>" > $fname.c
echo -e "/**\n * main - Entry point\n *\n * Return: Always 0 (Success)\n */\nint main(void)\n{\n\n*return (0);\n}" >> $fname.c
